## 📝 실전 문제풀이 Set 4: 디지털프라자 매출 데이터

### 1) 데이터 및 시나리오

▶ 디지털프라자 A지점에서 연휴 직전에 대대적인 할인 행사를 진행했다. 예상보다 많은 손님이 방문했고, 발생한 매출 데이터를 취합하여 향후 발송할 판촉물 컨텐츠를 기획하고자 한다. (1행 = 물품 1개 구매 내역)

* **데이터 개요:** `Xa sales_pos.csv` (550068 rows, 11 columns, UTF-8)

**[변수 상세]**

| 변수명 | 유형 | 설명 |
| --- | --- | --- |
| `user` | int | 고객 식별자 |
| `prod` | string | 상품 식별자 |
| `gender` | string | 성별 |
| `age_group` | string | 연령대 |
| `job` | int | 직업 구분 |
| `city` | string | 도시 유형 구분 |
| `marital` | int | 결혼 여부(1: 결혼) |
| `prod_cat1` | int | 상품 카테고리(1차) |
| `prod_cat2` | int | 상품 카테고리(2차) |
| `prod_cat3` | int | 상품 카테고리(3차) |
| `purchase` | int | 결제 금액 |

## 2) 문제

* **필요 라이브러리:** `MinMaxScaler`, `KMeans`, `silhouette_score`

In [5]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [ ]:
df = pd.read_csv('../dataset/sales_pos.csv')
display(df)

,user,prod,gender,age_group,job,city,marital,prod_cat1,prod_cat2,prod_cat3,purchase
0,1,P00069042,F,0-17,10,A,0,3,NaN,NaN,8370
1,1,P00248942,F,0-17,10,A,0,1,6.0,14.0,15200
2,1,P00087842,F,0-17,10,A,0,12,NaN,NaN,1422
3,1,P00085442,F,0-17,10,A,0,12,14.0,NaN,1057
4,2,P00285442,M,55+,16,C,0,8,NaN,NaN,7969
...,...,...,...,...,...,...,...,...,...,...,...
550063,6033,P00372445,M,51-55,13,B,1,20,NaN,NaN,368
550064,6035,P00375436,F,26-35,1,C,0,20,NaN,NaN,371
550065,6036,P00375436,F,26-35,15,B,1,20,NaN,NaN,137
550066,6038,P00375436,F,55+,1,C,0,20,NaN,NaN,365
550067,6039,P00371644,F,46-50,0,B,1,20,NaN,NaN,490

### **Q01.** 상품별 매출액(purchase)을 합산하여 그 매출액이 가장 큰 상품을 확인하고, **해당 상품을 가장 많이 구매하는 직업(job)을 확인하시오.**

* ※ 직업 확인 시 상품 구매 개수를 기준으로 확인하시오. 결과는 job 변수의 번호를 출력. (정답 예시: 1)

In [27]:
df_q1 = df.copy()
df_q1_gb_idxmax = df_q1.groupby(['prod'])['purchase'].sum().idxmax()

df_q1_job = df_q1[df_q1['prod'] == df_q1_gb_idxmax]['job'].value_counts()
df_q1_job.idxmax()

4

In [29]:
df_q1_ = df.copy()
df_q1_gb_ = df_q1_.groupby(['prod'])
display(df_q1_gb_)
display(df_q1_gb_.groups)

df_q1_job_ = df_q1[df_q1['prod'] == df_q1_gb_idxmax]['job'].value_counts()
display(df_q1_job_, type(df_q1_job_))

{'P00000142': [293, 1066, 1073, 1322, 1910, 2805, 3014, 3551, 3742, 5226, 5316, 5882, 6854, 7383, 8489, 9913, 10875, 11224, 11521, 11724, 11922, 12105, 12937, 13370, 13725, 14294, 14660, 14848, 15191, 15341, 15822, 16443, 16758, 18837, 19312, 20001, 20617, 22103, 22486, 23474, 23773, 24296, 24398, 24403, 25936, 27288, 27503, 28515, 28667, 29271, 29281, 29897, 29915, 30259, 30419, 30522, 31085, 31354, 31364, 31494, 31604, 31909, 32043, 32215, 32477, 32796, 34067, 34326, 34469, 34493, 35024, 35033, 35650, 36015, 36412, 36790, 36845, 37358, 38116, 38700, 41479, 41554, 42105, 42486, 43545, 43569, 44278, 44596, 44650, 45684, 45841, 45940, 47423, 47518, 47642, 47861, 48148, 48582, 49109, 49185, ...], 'P00000242': [11232, 12424, 16544, 19188, 19599, 20254, 20648, 20775, 22832, 23731, 28496, 28597, 30545, 31603, 32581, 34398, 34730, 35095, 36713, 36758, 37631, 38805, 39415, 39499, 39905, 40479, 41396, 43532, 45970, 47946, 48195, 48540, 50794, 52168, 53156, 58239, 59106, 60763, 61620, 62514, 63065, 63121, 64153, 64252, 65994, 67614, 69123, 73485, 73689, 75460, 77627, 78413, 80038, 82463, 85310, 89248, 94866, 96765, 98622, 104169, 105407, 105608, 106311, 108822, 110324, 111834, 112980, 113633, 114937, 114966, 116602, 117599, 118465, 119885, 123639, 125254, 126010, 126225, 126740, 127465, 128863, 129876, 131982, 133887, 134867, 136592, 137179, 138705, 139039, 141622, 142754, 142822, 143004, 143610, 143642, 144833, 146210, 146648, 147068, 147714, ...], 'P00000342': [2950, 16796, 21043, 22983, 32164, 33645, 37163, 37862, 38013, 38131, 40006, 40081, 41833, 42186, 42911, 43867, 46514, 48702, 49494, 49790, 50913, 52880, 53478, 53592, 54325, 54443, 63565, 65247, 65597, 67173, 68266, 73043, 79879, 79954, 80327, 81469, 81494, 82911, 85757, 88617, 89501, 93260, 98104, 100160, 101619, 103499, 108563, 109222, 111141, 111885, 116981, 117197, 118835, 120303, 121678, 127561, 134145, 139060, 139527, 140714, 142004, 145528, 146108, 146818, 151057, 151590, 151976, 160911, 167126, 167723, 168195, 171990, 172820, 173548, 178384, 181131, 183735, 191007, 192094, 193561, 193894, 195478, 197857, 198135, 200306, 201129, 203652, 204463, 206089, 206636, 210110, 210765, 213221, 214056, 216214, 219054, 220109, 221468, 222278, 224352, ...], 'P00000442': [3347, 31271, 36710, 49369, 62464, 65989, 69160, 86601, 88376, 104855, 109351, 110588, 114498, 114981, 116425, 116810, 118782, 137763, 151009, 151575, 154400, 162795, 162844, 168349, 173851, 175879, 186407, 198279, 202158, 216046, 218812, 219226, 222123, 232011, 234887, 234939, 240156, 240639, 246743, 253747, 256232, 260120, 270188, 272738, 272961, 274844, 275566, 283490, 286095, 292870, 308565, 310462, 310716, 315700, 318411, 319635, 326011, 327282, 329076, 342200, 344756, 350827, 351646, 357934, 370157, 373381, 373711, 374873, 379914, 383035, 384907, 391435, 392069, 392153, 396908, 403946, 406230, 413947, 415824, 423050, 423355, 433459, 442275, 448447, 457068, 461946, 489255, 497859, 501876, 515149, 516495, 526865], 'P00000542': [2292, 4719, 6522, 7125, 12441, 12765, 15055, 21489, 22984, 30632, 45924, 50943, 54297, 64797, 65508, 74321, 82275, 83121, 88749, 91269, 97567, 103438, 104033, 110682, 112438, 116534, 117797, 126814, 131023, 133235, 142564, 151313, 151918, 152590, 153404, 153413, 157501, 164104, 170735, 172489, 178944, 188538, 189421, 189874, 191424, 192766, 193582, 203863, 204993, 205877, 210338, 214318, 221076, 224910, 228309, 228312, 232271, 232507, 235380, 236264, 238289, 242206, 242545, 243773, 249540, 257409, 258623, 262984, 263533, 265456, 266117, 267211, 268296, 269300, 269593, 272320, 275592, 275827, 276977, 280035, 292830, 297006, 303194, 307716, 309822, 313661, 324159, 325622, 325889, 326373, 329587, 330243, 338387, 339787, 341798, 341935, 346378, 348332, 348829, 350736, ...], 'P00000642': [116, 301, 631, 663, 850, 3966, 4046, 4194, 4416, 4765, 6633, 7179, 7189, 7211, 9633, 9891, 10604, 10836, 12705, 12770, 15392, 15887, 19182, 19567, 19846, 20499, 22813, 23737, 24746, 24775, 25325, 26076, 26438, 28517, 28737, 28848, 32766, 34441, 35177, 36168, 37329, 44131, 44800, 47145, 47650, 47671, 47781, 47899, 48197, 49309, 49391, 49410, 50055, 50379, 51076, 53622, 54243, 54537, 55494, 55734, 59107, 59985, 60177, 61863, 61978, 62684, 62906, 63371, 64682, 65518, 65964, 66635, 68103, 68804, 68999, 72040, 73959, 74373, 75037, 75839, 76306, 76863, 80243, 80665, 83585, 84367, 86233, 87238, 87385, 88194, 89785, 89904, 90563, 91333, 93545, 94165, 95765, 95930, 96710, 96720, ...], 'P00000742': [7736, 9081, 10282, 14858, 16390, 16964, 19106, 27860, 30593, 32762, 34027, 36973, 40033, 41555, 43581, 44008, 48510, 49640, 49959, 51351, 54057, 55879, 58174, 60326, 61370, 63827, 67172, 69155, 69903, 70340, 72499, 75041, 75312, 76238, 76891, 78973, 80304, 81193, 82296, 86604, 86849, 87906, 87942, 88147, 91822, 93635, 96359, 96403, 98057, 100177, 100594, 100812, 106452, 107885, 108049, 111297, 112339, 115672, 117735, 118920, 121647, 124858, 128649, 129166, 129608, 130194, 130264, 138800, 140601, 142326, 144063, 144251, 147409, 150276, 151547, 152961, 158797, 161247, 161908, 163095, 164352, 170182, 171680, 171731, 178261, 181315, 184659, 188083, 190608, 192064, 192483, 194920, 196888, 197305, 197339, 201901, 206750, 208007, 208663, 213244, ...], 'P00000842': [6790, 35834, 39591, 40278, 46277, 51283, 53350, 65652, 86210, 91692, 108550, 116552, 135515, 142241, 155244, 231785, 232543, 234621, 244547, 263681, 268433, 303645, 325798, 346227, 355642, 366985, 371933, 390734, 399706, 405480, 406754, 423339, 446217, 456620, 482225, 532387], 'P00000942': [6217, 47021, 52208, 59375, 60186, 73017, 83973, 100054, 134493, 156656, 164763, 167666, 194966, 205797, 213005, 213562, 214866, 252514, 257234, 279346, 303660, 316313, 323768, 334813, 356393, 377841, 378346, 379136, 387131, 388866, 391290, 395365, 395885, 414880, 418697, 420749, 429282, 432056, 434980, 437911, 438667, 439326, 440427, 440512, 442254, 443012, 444095, 447326, 453074, 453893, 505596, 511271, 513890, 525513, 539370], 'P00001042': [1650, 2321, 4229, 4320, 6843, 7836, 7927, 8544, 9594, 12834, 14493, 14821, 16479, 16874, 18247, 18587, 20267, 20583, 21556, 23747, 26458, 27443, 28047, 29218, 29603, 31258, 32523, 34538, 35798, 36282, 38496, 38928, 39097, 39446, 39924, 43272, 47796, 48902, 49974, 52622, 53567, 54333, 54667, 55193, 57519, 57737, 58072, 58492, 59337, 60688, 60933, 61005, 62725, 62748, 63839, 66144, 68996, 71850, 72856, 75253, 75295, 76399, 77427, 77528, 78810, 79853, 82312, 83772, 84975, 85415, 87288, 89574, 92291, 93786, 93887, 95221, 95547, 96764, 97479, 99750, 100563, 101127, 102341, 102817, 102992, 104015, 104155, 106410, 107489, 108485, 109790, 109894, 111770, 113598, 114555, 118448, 118464, 119734, 120896, 121064, ...], 'P00001142': [708, 1896, 2942, 6881, 7499, 7636, 7723, 9318, 11351, 12490, 13913, 14447, 14696, 14973, 15272, 15516, 15665, 16450, 16845, 17415, 17921, 20905, 21262, 23190, 24948, 25218, 25620, 25820, 26279, 27134, 30144, 32288, 33196, 35309, 36210, 37980, 39879, 40158, 41672, 42451, 42606, 43319, 44604, 44967, 48555, 49347, 49405, 50946, 51464, 51986, 52919, 53293, 54671, 55290, 55479, 57070, 58931, 63825, 63838, 65771, 66184, 67277, 67976, 70590, 71622, 71887, 72303, 72518, 72814, 72973, 73216, 74018, 74123, 74514, 77260, 78359, 78391, 79220, 79875, 80646, 81529, 81584, 81815, 83837, 85230, 85729, 85859, 86091, 87992, 89234, 89647, 89805, 91314, 92885, 92935, 93065, 93585, 94015, 94207, 95103, ...], 'P00001242': [1533, 4028, 13313, 14616, 18439, 28541, 32642, 38418, 45514, 46746, 49002, 49547, 49753, 64772, 68407, 90676, 91304, 99195, 100241, 104531, 105533, 106133, 110293, 121455, 130316, 131519, 136676, 139586, 146238, 147848, 151250, 153293, 156024, 166305, 179926, 180289, 187598, 189671, 197089, 201285, 208279, 214796, 240459, 242214, 242324, 254542, 259811, 269879, 287629, 289350, 306286, 312914, 317781, 337726, 337860, 338243, 340739, 341400, 341621, 351990, 353414, 353916, 355941, 357523, 361429, 361451, 362041, 362459, 365286, 366697, 375918, 376264, 389231, 396234, 405587, 406356, 415897, 421990, 432156, 432228, 442219, 444904, 461193, 466100, 468238, 473616, 474463, 476747, 478387, 484268, 485603, 499229, 505065, 508016, 511415, 524303, 531078, 532246, 533252, 539753], 'P00001342': [12938, 14328, 20758, 29925, 30819, 38921, 39726, 42634, 44084, 57241, 58344, 61186, 63529, 92901, 99311, 126244, 135748, 140299, 143371, 153082, 166260, 181208, 188599, 198834, 199968, 215200, 221170, 225921, 227527, 228191, 229284, 239702, 242796, 250962, 269427, 282367, 286723, 301018, 302461, 311987, 319272, 324772, 325326, 353962, 381275, 419885, 454148, 456613, 457261, 459576, 470755, 477868, 481303, 496453, 497620, 503494, 512888, 516494, 526325, 527139, 531002, 538985], 'P00001442': [6141, 8109, 10215, 12398, 13842, 28323, 30397, 37658, 38914, 42301, 50115, 72933, 78539, 110369, 113317, 115360, 123772, 125242, 126315, 131567, 134985, 138542, 139332, 140272, 157454, 165855, 167123, 176174, 178837, 185784, 187430, 188457, 189871, 193967, 197291, 199533, 212325, 216394, 222454, 222926, 242086, 242508, 245519, 248160, 260295, 261355, 267123, 267683, 272497, 291218, 300126, 303976, 311739, 317836, 319910, 351419, 354702, 358544, 358703, 361460, 391828, 392263, 396125, 397643, 398308, 400400, 402900, 403998, 443030, 443576, 451983, 453737, 457330, 461951, 464734, 468684, 477088, 480945, 483595, 484096, 519105, 521805, 531040, 539951, 541767], 'P00001542': [1862, 7699, 13450, 20307, 22764, 22905, 24436, 25561, 26565, 26848, 45549, 47970, 49439, 57238, 72793, 76733, 88842, 91222, 98749, 103708, 105549, 112673, 117606, 118365, 118860, 137367, 153756, 156100, 159847, 166663, 181309, 191288, 203653, 234370, 237178, 239119, 239643, 252880, 254797, 257094, 262476, 264527, 266113, 271197, 275830, 276492, 293204, 302367, 321040, 330766, 335069, 347072, 353948, 360291, 375004, 377953, 380376, 382746, 412457, 433551, 452605, 460070, 467925, 469163, 472965, 476212, 506495, 532255, 537888], 'P00001642': [169, 456, 2846, 4576, 4741, 6007, 6941, 7107, 7516, 8044, 8330, 9038, 9065, 10456, 10878, 11342, 14697, 16062, 16696, 17334, 18102, 18847, 19251, 21887, 23582, 25799, 26722, 29290, 32365, 32470, 33397, 33513, 33560, 35329, 35516, 37441, 37752, 41066, 42220, 44184, 45801, 49923, 50810, 51246, 51904, 51967, 53265, 54000, 57326, 59097, 59498, 61595, 62631, 62682, 62827, 63113, 63338, 63785, 66134, 70136, 70307, 70712, 74564, 77498, 78107, 79000, 79304, 81151, 86424, 88432, 89991, 90545, 90910, 91607, 91708, 92425, 93570, 95182, 95875, 97596, 98238, 101475, 102651, 105481, 105964, 106008, 107338, 107533, 108045, 109655, 110026, 117386, 118333, 122055, 122075, 125814, 129048, 135184, 135601, 138399, ...], 'P00001742': [530, 606, 2141, 2587, 5933, 6979, 7246, 7941, 10937, 12965, 17083, 19663, 20542, 21265, 21529, 25894, 29044, 31498, 32286, 34208, 34225, 34905, 37936, 39089, 39171, 39921, 41187, 44766, 45233, 46587, 48804, 49586, 50044, 51381, 52316, 56455, 57011, 57972, 58835, 59168, 70778, 71818, 73183, 75728, 76523, 76878, 77707, 78456, 78538, 79640, 80712, 83338, 84654, 85475, 85931, 86104, 87131, 87331, 88227, 88414, 90343, 90926, 92585, 93968, 96488, 97530, 99249, 100435, 100708, 100947, 101313, 101598, 102119, 102626, 103501, 104769, 106380, 108067, 108948, 109484, 110361, 111067, 111156, 111611, 112068, 112312, 112514, 114149, 114225, 115097, 115828, 115867, 115964, 116324, 117074, 118544, 119887, 120645, 121866, 121916, ...], 'P00001842': [8772, 20395, 35766, 39487, 58295, 60713, 67312, 68382, 70581, 73839, 86612, 102802, 104062, 107436, 108156, 118324, 119841, 122877, 123708, 143389, 143619, 160753, 164438, 177132, 177345, 196455, 196749, 215719, 216517, 221479, 224651, 231156, 235168, 241982, 263407, 279844, 282790, 283105, 293448, 295005, 295191, 301630, 309670, 315738, 315875, 321124, 328506, 337626, 338229, 344071, 353538, 372791, 375317, 376015, 386507, 389683, 394875, 399181, 400556, 404167, 411803, 421160, 422280, 427535, 432054, 438419, 452398, 452694, 471153, 471657, 476700, 480516, 486057, 503223, 508323, 508732], 'P00001942': [490, 6185, 7720, 19761, 20740, 21397, 29600, 30304, 31321, 38291, 38644, 41532, 45952, 46738, 49667, 52100, 53274, 58515, 59415, 62078, 63207, 65441, 67245, 67362, 68268, 76429, 88510, 91987, 92526, 93158, 93205, 93354, 94553, 95011, 95433, 102597, 102746, 103109, 104131, 106543, 111925, 115262, 129381, 135111, 136267, 140143, 140839, 143058, 144501, 144994, 146416, 154109, 154220, 160709, 160807, 162199, 162570, 163710, 165650, 169306, 174696, 176860, 177765, 181470, 182552, 186215, 196329, 196460, 203548, 206205, 206664, 207835, 209617, 214783, 217643, 220559, 220589, 225005, 228670, 231436, 235586, 236880, 236926, 237502, 238692, 247662, 249987, 253082, 257176, 268023, 275831, 279478, 279799, 281866, 283939, 284082, 285806, 285836, 286256, 286343, ...], 'P00002042': [2323, 2849, 10887, 14287, 18504, 21464, 22716, 26784, 39002, 45090, 53616, 59407, 73738, 80122, 82204, 104945, 106541, 106785, 109189, 115572, 117512, 117965, 124185, 125212, 129985, 140015, 143826, 168184, 170915, 176951, 190235, 193188, 197686, 198842, 199218, 202253, 205095, 205261, 208914, 209221, 214868, 219140, 235763, 238133, 243699, 246173, 256913, 257112, 273978, 282064, 283983, 292881, 297107, 300732, 303168, 311490, 312781, 315447, 339378, 339963, 346398, 351701, 373400, 373448, 386761, 398754, 401717, 405245, 427848, 433351, 434928, 447790, 449731, 456487, 468276, 473895, 476458, 478241, 481273, 486543, 495461, 497207, 504256, 505052, 511225, 512753, 513740, 524955, 527652, 529746, 531490, 539701, 544246], 'P00002142': [1097, 2045, 2371, 2689, 3673, 6049, 7060, 8261, 8503, 9384, 9837, 10593, 12870, 13044, 14314, 14929, 14998, 15444, 15565, 15819, 16439, 16476, 18188, 18608, 19572, 19731, 21092, 22003, 24173, 24325, 25350, 25683, 27508, 27819, 28067, 28884, 29330, 30243, 30433, 31064, 33545, 34192, 34446, 34919, 35592, 36799, 36829, 36860, 37531, 37856, 38595, 39928, 42450, 44299, 47137, 47825, 47873, 48825, 49160, 50327, 50524, 50756, 51524, 51732, 52070, 52489, 52507, 52966, 53249, 54231, 55568, 56273, 57154, 58455, 59642, 60907, 62185, 63137, 63225, 65256, 65579, 65786, 66515, 66720, 67417, 68054, 69367, 69800, 70434, 71881, 72041, 72448, 72622, 72807, 72992, 72995, 73699, 74276, 75723, 76793, ...], 'P00002242': [3193, 4099, 4282, 6632, 7302, 18754, 18826, 19048, 19345, 19658, 24748, 26247, 27740, 29663, 31452, 36724, 38930, 45095, 51282, 52233, 52990, 56866, 69220, 69422, 70100, 77271, 80885, 85980, 89430, 91198, 92373, 93027, 93159, 100630, 105524, 116349, 119236, 126783, 130637, 138247, 142435, 145755, 147745, 150942, 151427, 152179, 154467, 156765, 158682, 167193, 168325, 170241, 174626, 175544, 179032, 179218, 182194, 182639, 183533, 183666, 183690, 183941, 184761, 193023, 193688, 196047, 198678, 198829, 202250, 202954, 204613, 208720, 209121, 215532, 215922, 222918, 224824, 230845, 233101, 233606, 236153, 239972, 244951, 246460, 248439, 250832, 254436, 259992, 263994, 265572, 266193, 269808, 273990, 274758, 276037, 278974, 281567, 288028, 293793, 295584, ...], 'P00002342': [4724, 6455, 9436, 24638, 35904, 57893, 60965, 86311, 104715, 105254, 120725, 124209, 145310, 177268, 178834, 179786, 191745, 192778, 194837, 198672, 212150, 212619, 212840, 223822, 247382, 251354, 255796, 256906, 271396, 274556, 284260, 291749, 293347, 297771, 300617, 303496, 324519, 325718, 325882, 330627, 344574, 361531, 362454, 363839, 366410, 369335, 374754, 380619, 380914, 383548, 411557, 416186, 423803, 447302, 449708, 452497, 456882, 461479, 469782, 476234, 494115, 509663, 520599, 529371, 532784, 534061, 544518], 'P00002442': [2975, 3150, 4383, 10873, 15865, 16281, 17591, 20984, 21018, 21165, 21426, 21725, 22007, 23306, 25844, 28730, 29961, 31278, 35630, 39696, 42691, 43275, 44340, 45404, 46264, 47690, 54023, 56504, 56899, 58324, 58862, 60379, 61445, 62939, 64704, 64759, 64965, 65742, 66198, 67899, 70595, 71846, 72641, 73237, 73915, 74480, 75150, 77420, 78577, 80597, 82170, 83287, 85913, 89126, 89976, 93975, 96788, 100363, 101269, 101664, 102014, 102055, 102381, 104191, 106447, 106548, 107196, 107705, 108517, 109110, 111054, 111956, 113514, 113783, 113804, 117966, 118573, 120270, 120309, 123129, 124567, 125070, 125248, 127750, 127767, 131428, 132897, 134217, 134550, 135540, 136636, 137879, 138972, 139880, 141555, 144282, 144759, 145786, 148891, 152916, ...], 'P00002542': [363, 746, 880, 1592, 2105, 3027, 5196, 5742, 5874, 6356, 6951, 8080, 11362, 11562, 12216, 12601, 14130, 14309, 16370, 18658, 18672, 19575, 20072, 20423, 21013, 21822, 24084, 28701, 29320, 30508, 31751, 32132, 32615, 34760, 35064, 35136, 35551, 37530, 38470, 39177, 43202, 44576, 45030, 45962, 49914, 50106, 50622, 51209, 51966, 52240, 52445, 53283, 53737, 55457, 55587, 58048, 58211, 58313, 58618, 59988, 60292, 60380, 61190, 62853, 63601, 64634, 65505, 66500, 66615, 67273, 68312, 69384, 69529, 69765, 70161, 71323, 71508, 73887, 74314, 74510, 75238, 75802, 77818, 78766, 79082, 79200, 81670, 82995, 83805, 85712, 88621, 89687, 89822, 91448, 92905, 93075, 93138, 93404, 94738, 94884, ...], 'P00002642': [1413, 16483, 50953, 60160, 60753, 66338, 67274, 83508, 92541, 100035, 123979, 139540, 148987, 151944, 154772, 162363, 164190, 164525, 181444, 199053, 209480, 215377, 238931, 247373, 247753, 251136, 256004, 263329, 264228, 264798, 265526, 272908, 273193, 278557, 282574, 286012, 297352, 315522, 340191, 344092, 356542, 360042, 374341, 378937, 386836, 386857, 389478, 398418, 400394, 401123, 405396, 417255, 422982, 436515, 441995, 442724, 456848, 461243, 489425, 514668, 524712, 530344, 545541], 'P00002742': [20773, 40841, 42050, 85146, 108713, 112369, 118009, 119974, 134690, 150878, 174918, 189887, 222941, 243993, 245626, 256109, 256435, 259518, 271373, 275687, 309795, 313875, 369142, 379886, 399330, 421276, 435563, 435886, 460141, 462893, 470364, 480494, 484091, 496892, 507824, 509381, 509972, 519955, 535477, 542463], 'P00002842': [21574, 22575, 23211, 24884, 31676, 36977, 37457, 40255, 54145, 54868, 74913, 81886, 85536, 89291, 90326, 97942, 107052, 115578, 136796, 156374, 163467, 185448, 187176, 187217, 187399, 190210, 190252, 207047, 210193, 213673, 219917, 221993, 231675, 244013, 272127, 272146, 280926, 283532, 289960, 296022, 302923, 307990, 311196, 316586, 320636, 329809, 345904, 356834, 363120, 367115, 367450, 370223, 392876, 395183, 397219, 410129, 411296, 419721, 422023, 422522, 428052, 435079, 436206, 436646, 440445, 451693, 462389, 466662, 470920, 474690, 475001, 479745, 484959, 486283, 489720, 497570, 498052, 504778, 505808, 506449, 506762, 532158, 534367, 542727], 'P00002942': [1444, 2917, 3595, 13812, 14643, 18639, 18742, 20011, 21486, 22641, 23310, 38549, 40163, 44406, 44500, 47041, 47259, 47995, 48820, 49501, 68357, 70432, 71006, 71461, 73269, 73665, 81148, 97780, 98560, 106924, 108513, 108739, 110038, 111766, 112659, 113618, 114181, 116207, 117167, 120396, 121459, 121585, 125909, 127961, 129063, 129475, 130467, 135073, 135941, 136355, 147995, 149375, 152211, 154958, 156687, 161947, 166773, 174345, 176893, 184180, 186603, 187332, 189314, 189406, 189761, 191005, 191885, 195880, 199841, 201811, 205694, 224592, 228867, 232175, 235788, 237989, 238895, 239527, 243327, 243488, 246537, 246924, 249865, 252318, 252460, 255512, 255685, 255944, 263050, 263171, 265374, 265393, 266196, 266624, 267984, 269854, 273092, 276285, 276731, 278407, ...], 'P00003042': [9909, 28874, 32548, 33071, 51152, 60559, 69829, 80882, 95090, 98579, 127375, 147740, 152155, 189995, 194754, 205028, 213299, 240173, 273731, 278624, 303769, 305920, 345942, 358816, 386310, 400103, 401106, 410051, 414045, 415802, 432894, 446292, 457425, 461489, 468729, 522950, 536995], 'P00003142': [9546, 12164, 24232, 24657, 28473, 33760, 36974, 43363, 45650, 54496, 55016, 56787, 61336, 67394, 72111, 72794, 80344, 85144, 89567, 95986, 97598, 104184, 110371, 111166, 113292, 123498, 134224, 137687, 141647, 143349, 144666, 150424, 151214, 164622, 169469, 170356, 179412, 190815, 198590, 200552, 201909, 212625, 217184, 217875, 223317, 230397, 2

4     221
7     187
0     179
17    143
1     124
12    117
14     84
2      78
20     75
16     60
10     55
6      54
15     50
3      46
11     38
5      31
13     24
19     20
18     14
9      12
8       3
Name: job, dtype: int64

pandas.core.series.Series

### **Q02.** 결혼 여부(marital)에 따라 구매하는 물품 종류 차이를 확인하고자 한다. 비교적 신혼부부가 많은 26-35세 그룹을 대상으로 각 고객의 구매물품 카테고리 개수를 산출하고, **결혼여부별로 그 평균값의 차이를 산출하시오.**

* ※ 구매 물품 카테고리 개수 산출에는 prod_cat1, 2, 3을 사용하며 결측치는 0으로 대치한다.
* ※ 카테고리 처리 예시: `prod_cat1=1, prod_cat2=2, prod_cat3=0` -> `1-2-0`
* ※ 정답은 절대값을 반올림하여 소수점 둘째 자리까지 출력하시오. (정답 예시: 0.12)

In [69]:
df_q2 = df[df['age_group'] == '26-35'].copy()
display(df_q2)
display(df_q2['prod_cat1'].apply(type).value_counts())
display(df_q2['prod_cat2'].apply(type).value_counts())
display(df_q2['prod_cat3'].apply(type).value_counts())
display(df_q2['age_group'].apply(type).value_counts())
display(df_q2['age_group'].unique())

col = ['prod_cat1','prod_cat2','prod_cat3']
df_q2[col] = df_q2[col].fillna(0).astype(int).astype(str)

df_q2['comb'] = df_q2['prod_cat1'] + "-" + df_q2['prod_cat2'] + "-" + df_q2['prod_cat3']
display(df_q2['comb'].unique())
display(df_q2['comb'].nunique())
display(df_q2['comb'].apply(type).value_counts())
display(df_q2)

,user,prod,gender,age_group,job,city,marital,prod_cat1,prod_cat2,prod_cat3,purchase
5,3,P00193542,M,26-35,15,A,0,1,2.0,NaN,15227
9,5,P00274942,M,26-35,20,A,1,8,NaN,NaN,7871
10,5,P00251242,M,26-35,20,A,1,5,11.0,NaN,5254
11,5,P00014542,M,26-35,20,A,1,8,NaN,NaN,3957
12,5,P00031342,M,26-35,20,A,1,8,NaN,NaN,6073
...,...,...,...,...,...,...,...,...,...,...,...
550058,6024,P00372445,M,26-35,12,A,1,20,NaN,NaN,121
550059,6025,P00370853,F,26-35,1,B,0,19,NaN,NaN,48
550061,6029,P00372445,F,26-35,1,C,1,20,NaN,NaN,599
550064,6035,P00375436,F,26-35,1,C,0,20,NaN,NaN,371
550065,6036,P00375436,F,26-35,15,B,1,20,NaN,NaN,137

<class 'int'>    219587
Name: prod_cat1, dtype: int64

<class 'float'>    219587
Name: prod_cat2, dtype: int64

<class 'float'>    219587
Name: prod_cat3, dtype: int64

<class 'str'>    219587
Name: age_group, dtype: int64

array(['26-35'], dtype=object)

array(['1-2-0', '8-0-0', '5-11-0', '1-2-5', '1-5-15', '5-14-0', '1-8-14',
       '6-8-0', '5-8-14', '8-17-0', '8-13-0', '1-6-0', '5-8-0', '1-8-0',
       '8-16-0', '1-16-0', '1-2-6', '1-6-14', '5-0-0', '5-15-0', '2-4-0',
       '5-8-18', '1-8-9', '2-0-0', '2-17-0', '13-16-0', '8-14-17',
       '4-8-9', '1-2-15', '1-15-16', '5-9-14', '7-0-0', '8-13-15',
       '16-0-0', '1-8-16', '1-6-15', '8-15-0', '4-5-9', '4-5-0', '15-0-0',
       '1-8-17', '1-15-0', '3-5-0', '1-6-8', '1-14-0', '1-2-16',
       '11-13-16', '18-0-0', '5-17-0', '1-14-17', '8-9-14', '1-11-15',
       '1-13-16', '1-6-16', '1-5-14', '3-15-0', '6-8-15', '11-15-0',
       '12-14-0', '3-4-5', '6-8-10', '6-8-13', '6-8-16', '1-2-8',
       '10-16-0', '3-4-12', '8-15-16', '15-16-0', '8-10-0', '1-2-13',
       '5-9-0', '1-2-3', '1-14-16', '1-0-0', '8-14-0', '5-6-9', '2-9-15',
       '1-2-9', '11-0-0', '5-12-0', '6-16-0', '1-2-14', '1-5-18',
       '10-15-16', '13-0-0', '1-2-11', '6-8-14', '2-8-14', '3-0-0',
       '8-14-16', '5-6-0', '5-12-14', '5-11-12', '4-5-12', '10-13-16',
       '1-11-0', '5-8-12', '6-13-0', '1-8-13', '10-15-0', '3-4-0',
       '4-5-8', '6-0-0', '8-12-0', '1-5-6', '5-8-17', '2-5-0', '8-11-0',
       '1-5-0', '14-0-0', '2-4-5', '15-17-0', '2-16-0', '2-6-15',
       '8-16-17', '2-8-18', '6-10-13', '2-8-0', '2-15-0', '4-9-15',
       '12-0-0', '1-5-17', '2-5-8', '1-15-17', '1-8-18', '5-13-0',
       '11-16-0', '11-14-0', '3-4-9', '2-3-4', '3-12-0', '10-0-0',
       '1-5-12', '5-16-0', '1-18-0', '6-10-0', '5-6-13', '8-13-16',
       '5-6-8', '2-4-8', '13-14-16', '5-18-0', '17-0-0', '6-10-16',
       '3-5-16', '5-14-16', '7-8-0', '1-17-0', '2-9-14', '2-12-0',
       '7-17-0', '2-4-9', '4-5-18', '2-3-15', '1-6-13', '2-14-0',
       '2-3-10', '5-14-17', '2-5-15', '8-10-16', '1-5-9', '11-15-16',
       '2-15-16', '1-4-9', '10-13-0', '13-15-16', '5-11-16', '1-8-15',
       '8-9-0', '13-15-0', '5-13-16', '6-11-13', '5-8-15', '1-11-16',
       '5-6-16', '2-9-0', '12-14-17', '5-7-0', '5-15-18', '1-2-18',
       '1-16-17', '8-12-17', '1-15-18', '4-8-0', '8-13-14', '10-14-16',
       '2-4-15', '6-11-16', '4-5-13', '8-18-0', '3-4-8', '1-2-17',
       '2-8-16', '2-14-15', '5-13-14', '1-14-15', '14-16-0', '1-5-8',
       '7-12-0', '2-5-12', '9-15-0', '5-14-15', '1-13-14', '1-2-4',
       '1-3-4', '15-16-17', '5-6-11', '11-13-0', '2-18-0', '2-4-12',
       '8-14-15', '6-11-0', '4-12-0', '2-5-14', '5-8-16', '8-11-16',
       '1-4-0', '4-5-15', '4-11-0', '12-17-0', '1-13-15', '4-15-0',
       '4-9-12', '14-17-0', '4-0-0', '2-12-14', '2-4-14', '3-13-0',
       '5-11-15', '4-9-0', '8-14-18', '14-18-0', '5-10-16', '19-0-0',
       '20-0-0'], dtype=object)

235

<class 'str'>    219587
Name: comb, dtype: int64

,user,prod,gender,age_group,job,city,marital,prod_cat1,prod_cat2,prod_cat3,purchase,comb
5,3,P00193542,M,26-35,15,A,0,1,2,0,15227,1-2-0
9,5,P00274942,M,26-35,20,A,1,8,0,0,7871,8-0-0
10,5,P00251242,M,26-35,20,A,1,5,11,0,5254,5-11-0
11,5,P00014542,M,26-35,20,A,1,8,0,0,3957,8-0-0
12,5,P00031342,M,26-35,20,A,1,8,0,0,6073,8-0-0
...,...,...,...,...,...,...,...,...,...,...,...,...
550058,6024,P00372445,M,26-35,12,A,1,20,0,0,121,20-0-0
550059,6025,P00370853,F,26-35,1,B,0,19,0,0,48,19-0-0
550061,6029,P00372445,F,26-35,1,C,1,20,0,0,599,20-0-0
550064,6035,P00375436,F,26-35,1,C,0,20,0,0,371,20-0-0
550065,6036,P00375436,F,26-35,15,B,1,20,0,0,137,20-0-0

In [105]:
df_q2_user_category_count = df_q2.groupby(['user', 'marital'])['comb'].nunique().reset_index(name='comb_count')
df_q2_marital = df_q2_user_category_count.groupby('marital')['comb_count'].mean()
display(df_q2_marital)
round(abs(df_q2_marital[0] - df_q2_marital[1]), 2)

marital
0    41.663183
1    41.792336
Name: comb_count, dtype: float64

0.13

### **Q03.** 고객 5891명을 군집화하여 마케팅 전략을 수립하고자 한다. 제시된 변수(성별, 구매 상품 종류수, 나이, 직업, 총 구매금액, 도시, 결혼 여부)를 대상으로 **k-means 군집분석(K=7)을 실시했을 때 Silhouette score를 산출하시오.**

* ※ 성별 변수는 M=1, F=0으로 변환, 나이는 순서형(0~6)으로 변환, 직업과 도시는 One Hot Encoding.
* ※ 사용 변수는 총 29개이며 MinMax 정규화 후 분석. seed는 123. (정답 예시: 0.12)

고객 5891명을 군집화하여 마케팅 전략을 수립하고자 한다. 제시된 변수(성별, 구매 상품 종류수, 나이, 직업, 총 구매금액, 도시, 결혼 여부)를 대상으로 **k-means 군집분석(K=7)을 실시했을 때 Silhouette score를 산출하시오.

-->

고객 5891명 별 제시된 변수(성별, 구매 상품 종류수, 나이, 직업, 총 구매금액, 도시, 결혼 여부)를 대상으로 ...
이므로 groupby가 떠오르게 되고, 저 변수들을 groupby 했을 때 그대로 쓰려면 agg로 활용한다.

**[변수 상세]**

| 변수명 | 유형 | 설명 |
| --- | --- | --- |
| `user` | int | 고객 식별자 |
| `prod` | string | 상품 식별자 |
| `gender` | string | 성별 |
| `age_group` | string | 연령대 |
| `job` | int | 직업 구분 |
| `city` | string | 도시 유형 구분 |
| `marital` | int | 결혼 여부(1: 결혼) |
| `prod_cat1` | int | 상품 카테고리(1차) |
| `prod_cat2` | int | 상품 카테고리(2차) |
| `prod_cat3` | int | 상품 카테고리(3차) |
| `purchase` | int | 결제 금액 |

In [204]:
df_q3 = df.groupby('user').agg(
    gender=('gender', 'first'),
    prod=('prod', 'nunique'),
    age_group=('age_group', 'first'),
    job=('job', 'first'),
    purchase=('purchase', 'sum'),
    city=('city', 'first'),
    marital=('marital', 'first') 
).reset_index() #groupby로 'user'가 index가 되니 'user'도 columns 으로 쓰기위함

display(df_q3.columns)
#gendor 변경
df_q3['gender'] = df_q3['gender'].replace({'M' : 1, 'F' : 0})

#age_group 변경
age_ = df_q3['age_group'].drop_duplicates().sort_values(ascending = True).reset_index(drop=True) #series 의 sorting
#display(age_)
age_dict = dict(zip(age_, age_.index))
#display(age_dict)
df_q3['age_group'] = df_q3['age_group'].replace(age_dict)


#modeling --
#D
#군집변수에는 user가 제외되어야 한다!!!
X_trained = pd.get_dummies(df_q3.drop(columns='user'), columns=['job','city'], drop_first=False)
display(X_trained.columns, len(X_trained.columns))

#N
scaler = MinMaxScaler()
X_trained_scaled = scaler.fit_transform(X_trained)
#M
model = KMeans(n_clusters = 7, random_state = 123, n_init = 10)
pred = model.fit_predict(X_trained_scaled)

#E
sil = silhouette_score(X_trained_scaled, pred)
display(sil)
round(sil, 2)

Index(['user', 'gender', 'prod', 'age_group', 'job', 'purchase', 'city',
       'marital'],
      dtype='object')

Index(['gender', 'prod', 'age_group', 'purchase', 'marital', 'job_0', 'job_1',
       'job_2', 'job_3', 'job_4', 'job_5', 'job_6', 'job_7', 'job_8', 'job_9',
       'job_10', 'job_11', 'job_12', 'job_13', 'job_14', 'job_15', 'job_16',
       'job_17', 'job_18', 'job_19', 'job_20', 'city_A', 'city_B', 'city_C'],
      dtype='object')

29

0.17879229751009443

0.18

In [158]:
display(df.columns)
df_q3 = df[['gender', 'prod', 'age_group', 'job','purchase','city','marital']].copy()
df_q3

display(df_q3['gender'].apply(type).value_counts(), df_q3['gender'].nunique(), df_q3['gender'].unique())
display(df_q3['age_group'].apply(type).value_counts(), df_q3['age_group'].nunique(), df_q3['age_group'].unique())
display(df_q3['job'].apply(type).value_counts(), df_q3['job'].nunique(), df_q3['job'].unique())
display(df_q3['city'].apply(type).value_counts(), df_q3['city'].nunique(), df_q3['city'].unique())

Index(['user', 'prod', 'gender', 'age_group', 'job', 'city', 'marital',
       'prod_cat1', 'prod_cat2', 'prod_cat3', 'purchase'],
      dtype='object')

<class 'str'>    550068
Name: gender, dtype: int64

2

array(['F', 'M'], dtype=object)

<class 'str'>    550068
Name: age_group, dtype: int64

7

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

<class 'int'>    550068
Name: job, dtype: int64

21

array([10, 16, 15,  7, 20,  9,  1, 12, 17,  0,  3,  4, 11,  8, 19,  2, 18,
        5, 14, 13,  6], dtype=int64)

<class 'str'>    550068
Name: city, dtype: int64

3

array(['A', 'C', 'B'], dtype=object)

In [160]:
# 고객 군집화
df['user'].nunique()

5891

In [155]:
# 성별 바꾸기 --> map
df_q3['gender'] = df_q3['gender'].map({'M' : 1,'F' : 0})
display(df_q3)

#age 바꾸기
age_group = df_q3['age_group'].drop_duplicates().sort_values()
age_group_pd = pd.Series(range(len(age_group)), index = age_group)
display(age_group_pd)
df_q3['age_group'] = df_q3['age_group'].replace(age_group_pd)
display(df_q3)

#one - hot encoding
df_q3 = pd.get_dummies(df_q3, columns=['job', 'city'], drop_first = False)
display(df_q3)

df_q3.shape

        gender       prod age_group  job  purchase city  marital
0            0  P00069042      0-17   10      8370    A        0
1            0  P00248942      0-17   10     15200    A        0
2            0  P00087842      0-17   10      1422    A        0
3            0  P00085442      0-17   10      1057    A        0
4            1  P00285442       55+   16      7969    C        0
...        ...        ...       ...  ...       ...  ...      ...
550063       1  P00372445     51-55   13       368    B        1
550064       0  P00375436     26-35    1       371    C        0
550065       0  P00375436     26-35   15       137    B        1
550066       0  P00375436       55+    1       365    C        0
550067       0  P00371644     46-50    0       490    B        1

[550068 rows x 7 columns]

age_group
0-17     0
18-25    1
26-35    2
36-45    3
46-50    4
51-55    5
55+      6
dtype: int64

        gender       prod  age_group  job  purchase city  marital
0            0  P00069042          0   10      8370    A        0
1            0  P00248942          0   10     15200    A        0
2            0  P00087842          0   10      1422    A        0
3            0  P00085442          0   10      1057    A        0
4            1  P00285442          6   16      7969    C        0
...        ...        ...        ...  ...       ...  ...      ...
550063       1  P00372445          5   13       368    B        1
550064       0  P00375436          2    1       371    C        0
550065       0  P00375436          2   15       137    B        1
550066       0  P00375436          6    1       365    C        0
550067       0  P00371644          4    0       490    B        1

[550068 rows x 7 columns]

,gender,prod,age_group,purchase,marital,job_0,job_1,job_2,job_3,job_4,...,job_14,job_15,job_16,job_17,job_18,job_19,job_20,city_A,city_B,city_C
0,0,P00069042,0,8370,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,P00248942,0,15200,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,P00087842,0,1422,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,P00085442,0,1057,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,1,P00285442,6,7969,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1,P00372445,5,368,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
550064,0,P00375436,2,371,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
550065,0,P00375436,2,137,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
550066,0,P00375436,6,365,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
550067,0,P00371644,4,490,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

(550068, 29)

In [157]:
#DNME

#D
X = df_q3

#N
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

#M
model = KMeans(n_clusters = 7, random_state = 123)
cluster = model.fit(X_scaled)

#E
sil = silhouette_score(X_scaled, cluster)
round(sil, 2)

ValueError: could not convert string to float: 'P00069042'